### ISSUE TITLE
1.13 MAP HEAD/DICT data missing

### ISSUE THREAD

**Issue by iamgreaser** [keendreams/keen#2]
This makes the 1.13 map data unusable without it. Do you have any intention on adding these in?

EGAHEAD/EGADICT are the same in 1.13 as in the repository.

**Comment by Blzut3** [comment]
I just downloaded 1.13 and KDREAMS.MAP has the same hash as 1.01S.  The 1.01S commit includes the different maphead/mapdict files.  Are you sure they're incorrect?

**Comment by iamgreaser** [comment]
MAPHEAD and MAPDICT match that of the 1.01S release, yeah. I should probably diff the 1.13 and 1.93 stuff and apply that to my fork.

Thanks for checking that out.
