### ISSUE TITLE
Apocalypse and Armageddan won't read

### ISSUE THREAD

**Issue by AJOgames** [keendreams/keen#5]
for some reason, refkeen has issues running Catacomb Apocalypse and Armageddan, and yes, SDL2.dll and libspeexdsp-1.dll is copied to each game folder, (I have individual folders for all the Catacomb games supported by RefKeen, each folder has their own SDL2.dll and libspeexdsp-1.dll, along with their own respective executable files)

I specifically downloaded Apocalypse and Armageddan from DJ OldGames, I later tried seeing if Terror and Curse of the Catacombs (The later versions of  Apoc. and Arma. re-released by Froggman) but they weren't read by Refkeen either

Do you plan on doing a similar source port like refkeen for Hovertank-3D?

here's a link to DJ OldGames, this link will take you to a page on the site that includes a download for Catacomb Apocalypse
http://www.oldgames.sk/en/game/catacomb-apocalypse-the/
Here is a screenshot showing the downloads

![oldgames](https://user-images.githubusercontent.com/42022618/44004887-2d65f138-9e1f-11e8-8ff0-aedeaccfd903.PNG)

**Comment by Blzut3** [comment]
This is not NY00123/refkeen.
